env: test
migrations_path: ./migrations

database:
  host: localhost
  port: 5432
  user: postgres
  password: user333
  name: medods
  sslmode: disable
  max_attempts: 5
  attemp_timeout: 10s
  attempt_delay: 5s

http_server:
  host: localhost
  port: 8080
  timeout: 5s
  idle_timeout: 1m

auth:
  access_token_lifetime: 1h
  refresh_token_lifetime: 168h
  access_secret: hajksfahskfhkashkf
  refresh_secret: asuyfioupfhkneqwIPUH